twig:
    default_path: '%kernel.project_dir%/templates'
    # utiliser bootstrap sur tous les formulaires
    # vendors/symfony/twig-bridge/Resources/Form
    form_themes: [ 'bootstrap_4_layout.html.twig' ]